global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'airflow'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow:8080']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
